"""Initial Migration

Revision ID: 4a617caad2de
Revises: dba699cb50e9
Create Date: 2019-09-20 19:19:46.680894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a617caad2de'
down_revision = 'dba699cb50e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'description')
    # ### end Alembic commands ###
