"""Initial Migration

Revision ID: 683b1c61544f
Revises: c97d8237b99b
Create Date: 2019-09-23 13:05:47.195673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683b1c61544f'
down_revision = 'c97d8237b99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    # ### end Alembic commands ###
