"""Initial Migration

Revision ID: dba699cb50e9
Revises: 0a310dab5fb8
Create Date: 2019-09-20 15:14:07.230521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba699cb50e9'
down_revision = '0a310dab5fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_pitches_description'), 'pitches', ['description'], unique=False)
    op.drop_index('ix_pitches_content', table_name='pitches')
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_pitches_content', 'pitches', ['content'], unique=False)
    op.drop_index(op.f('ix_pitches_description'), table_name='pitches')
    op.drop_column('pitches', 'description')
    # ### end Alembic commands ###
